### ISSUE TITLE
error node 

### ISSUE THREAD

**Issue by mikrotickets** [yandinovriandi/TunnelMikrotikBot#3]
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/root/TunnelMikrotikBot/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at createFsWatchInstance (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:49822:17)
    at setFsWatchListener (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:49869:15)
    at NodeFsHandler$1._watchWithNodeFs (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:50024:14)
    at NodeFsHandler$1._handleFile (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:50088:23)
    at NodeFsHandler$1._addToNodeFs (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:50330:21)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:51518:10)
    at NodeFsHandler$1._addToNodeFs (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:50338:18) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/root/TunnelMikrotikBot/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php',
  filename: '/root/TunnelMikrotikBot/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php'
}

Node.js v18.11.0
![Screenshot_135](https://user-images.githubusercontent.com/63126121/195963278-668b9c0d-6d86-422c-aea6-6f25989069c2.png)

**Comment by yandinovriandi** [comment]
> node:internal/errors:484 ErrorCaptureStackTrace(err); ^
> 
> Error: ENOSPC: System limit for number of file watchers reached, watch '/root/TunnelMikrotikBot/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php' at FSWatcher. (node:internal/fs/watchers:244:19) at Object.watch (node:fs:2315:34) at createFsWatchInstance (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:49822:17) at setFsWatchListener (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:49869:15) at NodeFsHandler$1._watchWithNodeFs (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:50024:14) at NodeFsHandler$1._handleFile (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:50088:23) at NodeFsHandler$1._addToNodeFs (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:50330:21) Emitted 'error' event on FSWatcher instance at: at FSWatcher._handleError (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:51518:10) at NodeFsHandler$1._addToNodeFs (file:///root/TunnelMikrotikBot/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:50338:18) { errno: -28, syscall: 'watch', code: 'ENOSPC', path: '/root/TunnelMikrotikBot/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php', filename: '/root/TunnelMikrotikBot/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php' }
> 
> Node.js v18.11.0 ![Screenshot_135](https://user-images.githubusercontent.com/63126121/195963278-668b9c0d-6d86-422c-aea6-6f25989069c2.png)

that'is error from supervisor, you can follow this article [https://parsinta.com/articles/mengatasi-error-saat-install-supervisor-vps-ubuntu-b6kcio](url)

**Comment by mikrotickets** [comment]
solution https://gist.github.com/bm2ilabs/617cab410f3cd93da777f1238bbc0349
